# You can use Placeholder API placeholders in these messages. To do so put the placeholder like <papi:placeholder> so for
# something like %player_username% you would do <papi:player_username> instead.
# Provided placeholders are <displayname> for display name, and <username> for user name
format:
  normal: "<displayname>"
  social-spy: "<username>"
  # Other messages can be configured in locale.yml
mysql:
  enabled: false
  ip: "localhost:3306"
  name: homes
  username: username1
  password: badpassword!
allow-messaging:
  hidden-players: false
  console: true
valid-console-names:
  - server
  - console
# This sends a specific message to console with the same socialspy format.
# Useful for searching logs, but also may cause clutter
console-has-social-spy: true
console-has-command-spy: false
command-spy:
  enabled: false
  commands: # have social spy also spy on these commands:
    - /minecraft:w
    - /minecraft:tell
    - /minecraft:msg
    - /minecraft:say
    - /minecraft:me
    - /minecraft:op
    - /op
    - /gmc
    - /gamemode
    - /give
sounds:
  received:
    enabled: false
    sound: minecraft:block.note_block.xylophone
    pitch: 1.8
    volume: 0.5
  sent:
    enabled: false
    sound: minecraft:entity.allay.item_thrown
    pitch: 1.8
    volume: 0.5
  spy:
    enabled: false
    sound: minecraft:entity.item_frame.rotate_item
    pitch: 1.8
    volume: 0.5
###
# This adds Webhook Support focused for Discord
###
webhook:
  enabled: false
  url: ""
  # This is the JSON Body to send to the webhook.
  # The default value is modeled after https://docs.discord.com/developers/resources/webhook#execute-webhook
  # These are the placeholders that can be used:
  #   <sender>: Sender's Username
  #   <sender_display_name>: Sender's Display Name (Nickname), Non-players will have the same name as <sender>
  #   <sender_uuid>: Sender's UUID, formatted as xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, this is blank for non-players.
  #   <recipient>: Recipient's Username
  #   <recipient_display_name>: Recipient's Display Name (Nickname), Non-players will have the same name as <recipient>
  #   <recipient_uuid>: Recipient's UUID, formatted as xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, this is blank for non-players.
  #   <message>: The message sent through SimplePMs.
  #   <timestamp>: Unix Timestamp (https://www.unixtimestamp.com/)
  json-body: |
    {
      "content": "{message}\n-# {sender_display_name} ({sender}) sent {recipient_display_name} ({recipient}) this on <t:{timestamp}>",
      "avatar_url": "https://mc-heads.net/avatar/{sender_uuid}",
      "username": "{sender} > {recipient}"
    }